// Comprehensive list of nationalities for standard CV and international job applications.
export interface NationalityOption {
  label: string;
  demonym: string;
  country: string;
}

export const NATIONALITIES: NationalityOption[] = [
  { label: 'Nepalese', demonym: 'Nepalese', country: 'Nepal' },
  { label: 'Romanian', demonym: 'Romanian', country: 'Romania' },
  { label: 'Bosnian', demonym: 'Bosnian', country: 'Bosnia & Herzegovina' },
  { label: 'Qatari', demonym: 'Qatari', country: 'Qatar' },
  { label: 'Indian', demonym: 'Indian', country: 'India' },
  { label: 'Filipino', demonym: 'Filipino', country: 'Philippines' },
  { label: 'Pakistani', demonym: 'Pakistani', country: 'Pakistan' },
  { label: 'Bangladeshi', demonym: 'Bangladeshi', country: 'Bangladesh' },
  { label: 'Sri Lankan', demonym: 'Sri Lankan', country: 'Sri Lanka' },
  { label: 'British', demonym: 'British', country: 'United Kingdom' },
  { label: 'German', demonym: 'German', country: 'Germany' },
  { label: 'Italian', demonym: 'Italian', country: 'Italy' },
  { label: 'French', demonym: 'French', country: 'France' },
  { label: 'Spanish', demonym: 'Spanish', country: 'Spain' },
  { label: 'Polish', demonym: 'Polish', country: 'Poland' },
  { label: 'Emirati', demonym: 'Emirati', country: 'United Arab Emirates' },
  { label: 'Saudi', demonym: 'Saudi', country: 'Saudi Arabia' },
  { label: 'American', demonym: 'American', country: 'United States' },
  { label: 'Canadian', demonym: 'Canadian', country: 'Canada' },
  { label: 'Australian', demonym: 'Australian', country: 'Australia' },
  { label: 'Egyptian', demonym: 'Egyptian', country: 'Egypt' },
  { label: 'Jordanian', demonym: 'Jordanian', country: 'Jordan' },
  { label: 'Kenyan', demonym: 'Kenyan', country: 'Kenya' },
  { label: 'Nigerian', demonym: 'Nigerian', country: 'Nigeria' },
  { label: 'Ghanaian', demonym: 'Ghanaian', country: 'Ghana' },
  { label: 'Turkish', demonym: 'Turkish', country: 'Turkey' },
  { label: 'Ukrainian', demonym: 'Ukrainian', country: 'Ukraine' },
  { label: 'Moldovan', demonym: 'Moldovan', country: 'Moldova' },
  { label: 'Hungarian', demonym: 'Hungarian', country: 'Hungary' },
  { label: 'Bulgarian', demonym: 'Bulgarian', country: 'Bulgaria' },
  { label: 'Serbian', demonym: 'Serbian', country: 'Serbia' },
  { label: 'Croatian', demonym: 'Croatian', country: 'Croatia' },
  { label: 'Slovak', demonym: 'Slovak', country: 'Slovakia' },
  { label: 'Czech', demonym: 'Czech', country: 'Czech Republic' },
  { label: 'Greek', demonym: 'Greek', country: 'Greece' },
  { label: 'Portuguese', demonym: 'Portuguese', country: 'Portugal' },
  { label: 'Dutch', demonym: 'Dutch', country: 'Netherlands' },
  { label: 'Belgian', demonym: 'Belgian', country: 'Belgium' },
  { label: 'Austrian', demonym: 'Austrian', country: 'Austria' },
  { label: 'Swiss', demonym: 'Swiss', country: 'Switzerland' },
  { label: 'Swedish', demonym: 'Swedish', country: 'Sweden' },
  { label: 'Norwegian', demonym: 'Norwegian', country: 'Norway' },
  { label: 'Danish', demonym: 'Danish', country: 'Denmark' },
  { label: 'Finnish', demonym: 'Finnish', country: 'Finland' },
  { label: 'Irish', demonym: 'Irish', country: 'Ireland' },
  { label: 'South African', demonym: 'South African', country: 'South Africa' },
  { label: 'Moroccan', demonym: 'Moroccan', country: 'Morocco' },
  { label: 'Tunisian', demonym: 'Tunisian', country: 'Tunisia' },
  { label: 'Indonesian', demonym: 'Indonesian', country: 'Indonesia' },
  { label: 'Malaysian', demonym: 'Malaysian', country: 'Malaysia' },
  { label: 'Vietnamese', demonym: 'Vietnamese', country: 'Vietnam' },
  { label: 'Chinese', demonym: 'Chinese', country: 'China' },
  { label: 'Japanese', demonym: 'Japanese', country: 'Japan' },
  { label: 'South Korean', demonym: 'South Korean', country: 'South Korea' },
  { label: 'Mexican', demonym: 'Mexican', country: 'Mexico' },
  { label: 'Brazilian', demonym: 'Brazilian', country: 'Brazil' },
  { label: 'Colombian', demonym: 'Colombian', country: 'Colombia' },
  { label: 'Argentine', demonym: 'Argentine', country: 'Argentina' },
];

export const GENDER_OPTIONS = [
  { label: 'Male', value: 'Male' },
  { label: 'Female', value: 'Female' },
  { label: 'Other', value: 'Other' },
  { label: 'Prefer not to say', value: 'Prefer not to say' },
];
